# Generated by Django 3.2.13 on 2022-04-12 16:07

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50, verbose_name='Nombre')),
                ('description', models.TextField(max_length=100, verbose_name='Descripción')),
                ('symbol', models.CharField(max_length=10, verbose_name='Símbolo')),
                ('market_values', models.JSONField()),
            ],
        ),
    ]
